### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by jennydaman** [twlinux/tricky#1]
- [ ] create node.js server
- wiki pages
  - [x] remote access (telnet and ssh)
  - [x] crypto
  - [x] systemd
  - [ ] tar, wget, curl
